dist: xenial
language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
      sudo: false
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.3
      dist: trusty
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install -U coverage nose python-coveralls

script:
  - nosetests --with-coverage --cover-package policy_generator
  - coveralls

after_sucess:
  coveralls